version: "3.9"

services:
  clonebot:
    image: ghcr.io/missemily2022/clonebot:new
    container_name: clonebot
    environment:
      - telegram_token=${1638543007:AAHW7IkG_S9ZyxXFZBbq73del051qXSYe5A}
      - user_ids=${420482391}
      - group_ids=${}
      - PORT=${8080}
    ports:
      - ${8080}:${8080}
    restart: unless-stopped
